### ISSUE TITLE
Feedback: Spectacular! and vector tile question

### ISSUE THREAD

**Issue by UGA-ITOSHumanitarianGIS** [wpgp/bottom-up-tutorial#10]
This is a question for perhaps enhancements and not an issue per se.  Vector tiles are packaged with admin boundaries and the SADD for Liberia. An example is here: https://stevage.github.io/vector-inspector/#?url=https://itos-humanitarian.s3.amazonaws.com/v1/VectorTile/COD_LBR/Admin/4/7/7.pbf&zyx&loc=6.76/6.78/-8.112

This is a prototype. Would this format and delivery be useful for this work? I see in figure 5 there are spreadsheets as the source with a sample map. Could the method be adapted to the vector tile for web? We are trying to gauge the demand for the vector tile cod-ab and cod-ps themes. Thanks for this resource and hope to hear back!

**Comment by edarin** [comment]
Thanks for your interest!.
I'm a bit confused. Are you suggesting to use a web-based service to retrieve polygons in order to aggregate population count?
Per se it's a good idea.
However in the section you're pointing to, we used a bespoke contour (around a group of settled pixels) for illustration purposes, and then we used it locally when processing the web page (from a .Rmd file) to compute the predicted population count. So we need a contour with which we can process GIS data.

Furthermore here we are in Nigeria not Liberia. But are your organisation interested in bottom-up population modelling? I see that for Liberia for example you have a complete datasets of population counts such that there is no missing population.

I would need to hear a bit more about the vector tile iniative to gauge how it can be used!
Happy to discuss it futher.

**Comment by UGA-ITOSHumanitarianGIS** [comment]
Thank you! These vector tiles are available with some caveats in the cod.unocha.org pipeline for many countries listed here: https://github.com/UGA-ITOSHumanitarianGIS/mapservicedoc/blob/master/Data/AWSDeploymentURLlist.xlsx and these were generated with the P-Code and names attribution and without population statistics. The population statistics may not be useful for the bottom up but perhaps there would be some useful projection or derivative with values intact. The specification is also based on the mapbox protobuf implementation. https://docs.mapbox.com/data/tilesets/guides/vector-tiles-standards/ The capability for these in many different uses from rendering in dashboards and map clients including leaflet as you have in this solution, so it would be very interesting to see where this may go in terms of how to generate vector tiles updates on the fly so to speak using these algorithms.  Feedback is very welcome, so that these may be generated based on stakeholders. We are about to publish another amalgamated dataset (cod-ab-ps) for Romania and as feedback come in, we may make adjustments to schema. There are also the ESRI vector tiles and gauging the use of those would be helpful. Thanks once again for this great work and we will check back but we will close this issue for now.
